command: ["python", "app.py"]
env:
  - name: DATABRICKS_APP_PORT
    value: "8000"
  # Database connection will be provided via the marketplace-database resource
  - name: DATABASE_RESOURCE_NAME
    valueFrom: "marketplace-database"
  # Lakebase database connection details will be automatically provided
  - name: LAKEBASE_DATABASE_NAME
    value: "marketplace_app"
  # Comma-separated list of admin users (email addresses recommended)
  # The system will check against email (from gap-auth header), username, and display_name
  # Example: "admin@company.com,user2@company.com"
  - name: MARKETPLACE_ADMIN_USERS
    value: "admin@company.com"